name: Build GluonFX App with Gradle

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download and Setup GraalVM
        run: |
          wget -q https://github.com/gluonhq/graal/releases/download/gluon-23%2B25.1-dev-2409082136/graalvm-java23-linux-amd64-gluon-23+25.1-dev.tar.gz
          tar -xzf graalvm-java23-linux-amd64-gluon-23+25.1-dev.tar.gz
          echo "GRAALVM_HOME=$PWD/graalvm-java23-linux-amd64-gluon-23+25.1-dev" >> $GITHUB_ENV
          echo "JAVA_HOME=$PWD/graalvm-java23-linux-amd64-gluon-23+25.1-dev" >> $GITHUB_ENV
          echo "$PWD/graalvm-java23-linux-amd64-gluon-23+25.1-dev/bin" >> $GITHUB_PATH

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Verify Setup
        run: |
          echo "JAVA_HOME=$JAVA_HOME"
          echo "GRAALVM_HOME=$GRAALVM_HOME"
          java -version
          ./gradlew --version
          native-image --version

      - name: Install required libraries for Linux
        run: |
          sudo apt-get update
          sudo apt-get install -y libasound2-dev libavcodec-dev libavformat-dev libavutil-dev libfreetype6-dev libgl-dev libglib2.0-dev libglib2.0-dev libgtk-3-dev libpango1.0-dev libx11-dev libxtst-dev

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build Desktop Native
        run: |
          ./gradlew clean build
          ./gradlew nativeBuild --stacktrace
          
      - name: Upload Desktop Build
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: desktop-linux-x64
          path: build/gluonfx/x86_64-linux/Prospect
          retention-days: 30
          if-no-files-found: warn

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 35
          build-tools: 35.0.0
          ndk: 23.1.7779620

      - name: Build Android APK
        run: |
          unset ANDROID_SDK_ROOT
          export ANDROID_HOME="${{ steps.setup-android.outputs.sdk-path }}"
          ./gradlew clean nativeBuild nativePackage -Ptarget=android --stacktrace
        env:
          ANDROID_HOME: ${{ steps.setup-android.outputs.sdk-path }}
        continue-on-error: true

      - name: Upload Android APK
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: android-apk
          path: build/gluonfx/aarch64-android/gvm/*.apk
          retention-days: 30
          if-no-files-found: ignore

      - name: Upload Gluon logs on failure
        uses: actions/upload-artifact@v4
        with:
          name: gluon-build-logs
          path: |
            build/gluonfx/log/*.log
            build/gluonfx/log/**/*.log
          retention-days: 30